### ISSUE TITLE
Question about downloading training data

### ISSUE THREAD

**Issue by ningrui-li** [magdalena-wysocki/ultra-nerf#1]
Hi Magdalena,

Thank you for sharing your work, this looks great! Could you please help me take a look at the link containing the training data ([here](https://syncandshare.lrz.de/getlink/fi3EGowa2yGEkUr3yZFUwn/))? When I try to go to the link, I get a message saying "This link is expired and cannot be used anymore."

Thank you!

**Comment by magdalena-wysocki** [comment]
Hi!

Thank you for letting me know! The link should be working now. Let me know should you have any more issues with the data.

Best, 
Magdalena

**Comment by ningrui-li** [comment]
Perfect, thank you again!

**Comment by Ontheroad123** [comment]
Hi Magdalena, i have  applied to download the training data with  qhe05412@gmail.com, can i be allowed to download for scientific research purposes?
