### ISSUE TITLE
How to compute the baseline 

### ISSUE THREAD

**Issue by Alphafrey946** [magdalena-wysocki/ultra-nerf#2]
Hi,

Thank you for sharing the code. I'm interested in reproducing some of the results in the paper. How do you train without the rendering forward model, and is code for the compounding method available? Thank you.

**Comment by magdalena-wysocki** [comment]
Hi, 

Thank you for your interest in our work, and for bringing it to my attention that I ,in fact, did not publish the code for the baseline. I will fix it. Meanwhile, to train without the forward rendering model, you need to adapt the code such that the output of the network is the intensity in the final B-mode image. The published code needs two adjustments:

1. In the configuration file the output channel should be set to 1
2. The rendering function should accept raw data and output intensity, e.g.

`intensity_map = tf.math.sigmoid(raw[..., 0])`

For the compounding I used [ImFusion Suite](https://www.imfusion.com/products/imfusion-suite). If you do not have access this this one, I think you can use any other compounding method. 

Best
Magdalena

**Comment by Alphafrey946** [comment]
Thank you.
